name: tailscale
icon: tailscale
type: vpn
title: Tailscale
hostname: tailscale
containers:
  - name: tailscale
    image: tailscale/tailscale
options:
  - version: '1.94'
    tag: 'v1.94.2'
labels:
  - openclaw

links:
- name: serve
  title: Service to serve
  required: false
  helm:
    - name: serve.host
      value: '{{link.service.name}}'
    - name: serve.port
      value: '{{link.service.mainPort.number}}'  
    - name: serve.protocol
      value: '{{link.service.mainPort.protocol}}'  
    - name: serve.namespace
      value: '{{link.instance.namespace}}'  
  selectors:
  - type: service
  - type: db
  - type: search
  - type: datastore


integrations:
- name: tailscale
  title: Tailscale
  type: vpn
  required: true
  multiple: false
  labels:
  - tailscale

volumes:
- name: state
  title: State
  size: 1
  optional: false
  helm: 
    labels: persistence.labels    
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.state.size}}Gi'

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/tailscale
  chart: oci://registry-1.docker.io/wodby/tailscale
  version: 0.1.0
  configurations:
    - name: tailscale
      labels: podLabels
      annotations: podAnnotations
      env: envVars
      resources: resources
      volumes: extraVolumes
      mounts: extraVolumeMounts
  values:
    - name: authKey
      value: '{{integrations.tailscale.key}}'    
    - name: tsHostname
      value: '{{links.serve.service.fqdnPrefix}}'
